name = "castwing"
compatibility_date = "2026-04-14"
main = "worker.js"

[assets]
directory = "."
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "castwing-db"
database_id = "fb8c4e61-e82c-4d75-aadd-f509e5612735"

[vars]
ADMIN_EMAILS = "sersoub.w@gmail.com"
