name = "castwing"
account_id = "2b8941187fc013611cd2dd5379ad0534"
compatibility_date = "2026-04-14"
main = "worker.js"

[assets]
directory = "."
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "castwing-db"
database_id = "fb8c4e61-e82c-4d75-aadd-f509e5612735"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "5b1939098b2b471eaa8e8155d4cae205"

[vars]
ADMIN_EMAILS = "sersoub.w@gmail.com"
